merge_queue:
  mode: serial
  max_parallel_checks: 1
queue_rules:
  - name: VM2 deleted head repo in-place freshness
    queue_conditions:
      - base = vm2-headrepo-delete-base-0916
    merge_conditions: []
    batch_size: 1
pull_request_rules:
  - name: VM2 autoqueue deleted head repo freshness
    conditions:
      - base = vm2-headrepo-delete-base-0916
    actions:
      queue:
